---
- hosts: riak_cluster
  sudo: True
  vars:
    ip_addr: ${ansible_${riak.iface}.ipv4.address}
  tasks:
  - include: ../roles/riak/tasks/prep_os.yaml

  - include: ../roles/riak/tasks/Ubuntu/main.yaml
    when_string: $ansible_distribution == 'Ubuntu'

  - include: ../roles/riak/tasks/configure.yaml

  handlers:
  - include: ../roles/riak/handlers/main.yaml

