---
# Handlers for HAproxy

- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: ufw
  shell: ufw allow haproxy && ufw app update haproxy