---
# configure the services
- hosts: stanchion[0]
  sudo: True
  tasks:
  vars_files:
   - roles/common/vars/main.yml

  tasks:
  - include: roles/stanchion/tasks/appconfig.yml anon='true' admin_key='foo' admin_secret='bar'
  - include: roles/riakcs/tasks/appconfig.yml anon='true' admin_key='foo' admin_secret='bar'
  - name: restart services
    service: name=$item state=restarted
    with_items:
     - stanchion
     - riak-cs
  - include: roles/stanchion/tasks/resetcreds.yml


# update the creds for safe keeping and subsequent runs
- hosts: 127.0.0.1
  connection: local
  vars_files:
  - roles/common/vars/resetcreds.yml

  tasks:
  - resetcreds: admin_key=${creds.admin_key} admin_secret=${creds.admin_secret}
# changes the stanchion creds on all the stanchion servers

- hosts: stanchion
  sudo: True
  vars_files:
  -  roles/common/vars/main.yml
  - roles/common/vars/resetcreds.yml

  tasks:
  - include: roles/stanchion/tasks/appconfig.yml

  handlers:
  - include: roles/stanchion/handlers/main.yml

# change creds on all the riakcs servers

- hosts: riak_cluster
  serial: 1
  sudo: True
  vars_files:
  - roles/common/vars/main.yml
  - roles/common/vars/resetcreds.yml

  tasks:
  - include: roles/riakcs/tasks/appconfig.yml

  handlers:
  - include: roles/riakcs/handlers/main.yml
