---
- name: configure /etc/stanchion/app.config
  template: src=etc_stanchion_app.config.j2 dest=/etc/stanchion/app.config
  tags: configfiles
  notify: restart stanchion

- name: configure vm.args
  template: src=etc_stanchion_vm.args.j2 dest=/etc/stanchion/vm.args
  tags: configfiles
  notify: restart stanchion

- name: start stanchion
  service: name=stanchion state=started