---
- name: install stanchion
  yum: name=stanchion state=present
  when: ansible_pkg_mgr == 'yum'

- name: install stanchion
  apt: pkg=stanchion update_cache=yes
  when: ansible_pkg_mgr == 'apt'

- name: set the stanchion ulimit
  copy: src=etc_default_stanchion_ulimit dest=/etc/default/stanchion
  when: ansible_pkg_mgr == 'apt'

- name: configure ulimit for stanchion user
  copy: src=etc_security_limits.d_stanchion.conf dest=/etc/security/limits.d/stanchion.conf

- name: configure /etc/stanchion/app.config
  template: src=etc_stanchion_app.config.j2 dest=/etc/stanchion/app.config
  tags: configfiles
  notify: restart stanchion

- name: configure vm.args
  template: src=etc_stanchion_vm.args.j2 dest=/etc/stanchion/vm.args
  tags: configfiles
  notify: restart stanchion

- name: start stanchion
  service: name=stanchion state=started enabled=yes