---
- name: configure app.config
  template: src=etc_riak_app.config.j2 dest=/etc/riak/app.config
  tags: configfiles

- name: make sure there are no transfers happening
  riak: wait_for_handoffs=true
  async: 600
  poll: 10

- name: stop riak
  service: name=riak state=stopped

- name: start riak
  service: name=riak state=started

- name: wait for riak_kv service to start
  riak: wait_for_service=kv
  async: 30
  poll: 1

- name: performs a test of the riak backend
  riak: command=kv_test