---
#configure ulimits

- name: set the riakcs ulimit
  copy: src=etc_default_riak-cs_ulimit dest=/etc/default/riak-cs

- name: configure ulimit for riak-cs user
  copy: src=etc_security_limits.d_riakcs.conf dest=/etc/security/limits.d/riakcs.conf

- name: configure iptables
  template: src=iptables.j2 dest=/etc/ufw/applications.d/riakcs owner=root group=root mode=0644
  notify:
  - ufw

- name: install riakcs
  apt: pkg=riak-cs

- name: configure /etc/riak-cs/app.config
  template: src=etc_riak-cs_app.config.j2 dest=/etc/riak-cs/app.config
  tags: configfiles
  notify: restart riakcs

- name: configure /etc/riak-cs/vm.args
  template: src=etc_riak-cs_vm.args.j2 dest=/etc/riak-cs/vm.args
  tags: configfiles
  notify: restart riakcs

- name: enable riak-cs
  service: name=riak-cs enabled=yes

- name: start riak-cs
  service: name=riak-cs state=started