---
#configure ulimits

- name: set the riakcs ulimit
  copy: src=etc_default_riak-cs_ulimit dest=/etc/default/riak-cs
  when: ansible_pkg_mgr == 'apt'

- name: configure ulimit for riak-cs user
  copy: src=etc_security_limits.d_riakcs.conf dest=/etc/security/limits.d/riakcs.conf

- name: install riakcs
  apt: pkg=riak-cs
  when: ansible_pkg_mgr == 'apt'

- name: install riakcs
  yum: name=riak-cs state=present
  when: ansible_pkg_mgr == 'yum'

- name: configure /etc/riak-cs/app.config
  template: src=etc_riak-cs_app.config.j2 dest=/etc/riak-cs/app.config
  tags: configfiles
  notify: restart riakcs

- name: configure /etc/riak-cs/vm.args
  template: src=etc_riak-cs_vm.args.j2 dest=/etc/riak-cs/vm.args
  tags: configfiles
  notify: restart riakcs

- name: start riakcs
  service: name=riak-cs state=started enabled=yes