---
- name: configure app.config
  template: src=etc_riak_app.config.j2 dest=/etc/riak/app.config
  tags: configfiles
  notify:
  - restart riak
  - wait for http
  - wait for kv

- name: configure vm.args
  template: src=etc_riak_vm.args.j2 dest=/etc/riak/vm.args
  tags: configfiles
  notify:
  - restart riak
  - wait for http
  - wait for kv

- name: start riak
  service: name=riak state=started
  notify:
  - wait for http
  - wait for kv