---
- name: install riak
  yum: name=riak state=present
  when: ansible_pkg_mgr == 'yum'

- name: install riak
  apt: pkg=riak update_cache=yes
  when: ansible_pkg_mgr == 'apt'

- name: set the riak ulimit
  copy: src=etc_default_riak_ulimit dest=/etc/default/riak
  when: ansible_pkg_mgr == 'apt'

- name: update pam configuration
  copy: src=etc_security_limits.d_riak.conf dest=/etc/security/limits.d/riak.conf owner=root group=root mode=0644

- name: configure app.config
  template: src=etc_riak_app.config.j2 dest=/etc/riak/app.config
  tags: configfiles
  notify:
  - restart riak

- name: configure vm.args
  template: src=etc_riak_vm.args.j2 dest=/etc/riak/vm.args
  tags: configfiles
  notify:
  - restart riak

- name: start riak
  service: name=riak state=started enabled=yes
  notify:
  - wait for http
  - wait for kv