---
# Handlers for HAproxy

- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restore iptables
  shell: iptables-restore < /etc/iptables.rules