---
- name: apt install riak-cs
  apt: pkg=riak-cs update_cache=yes
  when_string: $ansible_pkg_mgr == 'apt'

- name: yum install riak-cs
  yum: name=riak-cs state=present
  when_string: $ansible_pkg_mgr == 'yum'

- name: configure ulimit for riak-cs user
  copy: src=etc_security_limits.d_riakcs.conf dest=/etc/security/limits.d/riakcs.conf

- name: configure /etc/riak-cs/app.config
  template: src=etc_riak-cs_app.config.j2 dest=/etc/riak-cs/app.config
  tags: configfiles
  notify: restart riakcs

- name: configure /etc/riak-cs/vm.args
  template: src=etc_riak-cs_vm.args.j2 dest=/etc/riak-cs/vm.args
  tags: configfiles
  notify: restart riakcs