---
- name: configure /etc/riak-cs/app.config
  template: src=etc_riak-cs_app.config.j2 dest=/etc/riak-cs/app.config
  tags: configfiles
  notify: restart riakcs

- name: configure /etc/riak-cs/vm.args
  template: src=etc_riak-cs_vm.args.j2 dest=/etc/riak-cs/vm.args
  tags: configfiles
  notify: restart riakcs

- name: start riakcs
  service: name=riak-cs state=started